name: Pipeline CI/CD Python

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout - clone le code du projet
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil pycryptodome pyOpenSSL dnspython scapy


      - name: Run basic test
        run: |
          python app_cli_server.py --help || true
